
[[_usage]]
= Usage

The typical example is guaranteeing that only the creator of an object can edit its properties. Let's imagine a social network which publishes posts:

.Post.java
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/test/groovy/com/agorapulse/permissions/Post.java[lines=20..-1]
----

Only the author of the `Post` can update its state to either `publish` it or `archive` it. This can be achieved by
annotating the particular service methods with `@RequiresPermissions` annotation.

[[_require_permissions]]
== Require Permissions

.PostService.java
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/test/groovy/com/agorapulse/permissions/PostService.java[lines=20..-1]
----
<1> Require permission `edit` on the `Post` object `post`

The required permission is any arbitrary `String`. The semantics are given by specific implementation of the <<_permission_advisors, permission advisor>>.

In case of method having multiple arguments then every argument must pass the verification if particular  <<_permission_advisors, permission advisor>> is defined.
There must be <<_permission_advisors, permission advisor>> defined for at least one fo the arguments.

[[_permission_advisors]]
== Permission Advisors

The permissions are checked using the beans implementing `PermissionAdvisor<T>` interface.

.PermissionAdvisor.java
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/main/groovy/com/agorapulse/permissions/PermissionAdvisor.java[lines=20..-1]
----
TIP: `PermissionAdvisor` implements `Ordered` interface, so you can prioritize one advisor over another.

The following advisor will check if the current `User` is author of the `Post` instance.

.EditPostAdvisor.java
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/test/groovy/com/agorapulse/permissions/EditPostAdvisor.java[lines=20..-1]
----
<1> Declare the type of the argument being verified
<2> Return `UNKNOWN` if the status cannot be determined, next advisor will be asked for the result
<3> Return `ALLOW` if the user *can* perform the requested operation
<4> Return `DENY` if the user *cannot* perform the requested operation


If any advisor return `DENY` or every advisor returns `UNKNOWN` then the `PermissionException` is thrown.

[[_exception_handling]]
== Exception Handling

You can map `PermissionException` to `401 UNAUTHORIZED` using the `@Error` annotation within your HTTP environment.

.Handling `PermissionException` in Controller
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/test/groovy/com/agorapulse/permissions/PostController.java[tags=error,indent=0]
----

[[_user_retrieval]]
== User Retrieval

There is no predefined interface for retrieving the user but the best practise to create a very simple interface that
returns an `Optional`:

.UserProvider.java
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/test/groovy/com/agorapulse/permissions/UserProvider.java[lines=20..-1]
----

Then the example implementation can look like the following one:

.RequestScopeUserProvider.java
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/test/groovy/com/agorapulse/permissions/RequestUserProvider.java[lines=20..-1]
----
<1> Use `@Singleton` instead of `@RequestScope` if you want to use the advisors outside the controller calls (e.g. jobs)
<2> Use `ServerRequestContext` to retrieve the current request if present
<3> Check if the request already does not contain the user object
<4> Retrieving `User` can be potentially expensive operation
<5> Store the `User` in the request for the calls which may follow

[[_granting_permissions]]
== Granting Permissions

Sometimes you want to disable the check for a particular method calls. One of the examples could be and administrator access
or calling the code from serverless function.

In the following example you can see two options how to temporarily disable the permission checks.

.AdministratorPostService.java
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/test/groovy/com/agorapulse/permissions/AdministratorPostService.java[lines=20..-1]
----
<1> Using `@GrantPermissions` annotation to disable checks for the `post` object within the method body
<2> Disabling the checks just for the limited scope with `TemporaryPermissions` object
