
[[_usage]]
= Usage

The typical example guarantees that only the creator of an object can edit its properties. Imagine a social network which publishes posts:

.Post.java
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/test/groovy/com/agorapulse/permissions/Post.java[lines=20..-1]
----

Only the author of the `Post` can update its state to either `publish` it or `archive` it. This can be achieved by
annotating the associated service methods with the `@RequiresPermissions` annotation.

[[_require_permissions]]
== Require Permissions

.PostService.java
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/test/groovy/com/agorapulse/permissions/PostService.java[lines=20..-1]
----
<1> Require permission `edit` on the `Post` object `post`
<2> If you need to check the permissions on the returned object, use `@ResultRequiresPermission`
<3> You can use `@ResultRequiresPermission` with `returnNull = true` to return `null` instead of throwing exception effectively producing `NOT_FOUND` HTTP statuses in the controllers.

The permission can be any `String`. The semantics are given by the implementation of the <<_permission_advisors, permission advisor>>.

For methods with multiple arguments, every argument must pass verification by the defined  <<_permission_advisors, permission advisor>>.
There must be a <<_permission_advisors, permission advisor>> defined for at least one of the arguments.

It is possible to validate a typed Iterable argument, <<_permission_advisors, permission advisor>> will apply to all of its items based on their type defined in method signature.

[[_permission_advisors]]
== Permission Advisors

Permissions are checked by beans that implement `PermissionAdvisor<T>`.

.PermissionAdvisor.java
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/main/groovy/com/agorapulse/permissions/PermissionAdvisor.java[lines=20..-1]
----
TIP: `PermissionAdvisor` extends `Ordered` to support prioritizing one advisor over another.

The following advisor will check if the current `User` is the author of the `Post` instance.

.PostAdvisor.java
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/test/groovy/com/agorapulse/permissions/PostAdvisor.java[lines=20..-1]
----
<1> Declare the type of the argument being verified
<2> Return `UNKNOWN` if the status cannot be determined; the next advisor will be asked for the result
<3> Return `ALLOW` if the user *can* perform the requested operation
<4> Return `DENY` if the user *cannot* perform the requested operation

If any advisor returns `DENY`, or every advisor returns `UNKNOWN`, a `PermissionException` is thrown.

[[_exception_handling]]
== Exception Handling

You can map `PermissionException` to `401 UNAUTHORIZED` using the `@Error` annotation in your HTTP environment.

.Handling `PermissionException` in Controller
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/test/groovy/com/agorapulse/permissions/PostController.java[tags=error,indent=0]
----

[[_user_retrieval]]
== User Retrieval

There is no predefined interface for retrieving the user, but the best practise is to create a simple interface that
returns an `Optional`:

.UserProvider.java
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/test/groovy/com/agorapulse/permissions/UserProvider.java[lines=20..-1]
----

Then the example implementation can look like this:

.RequestScopeUserProvider.java
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/test/groovy/com/agorapulse/permissions/RequestUserProvider.java[lines=20..-1]
----
<1> Use `@Singleton` instead of `@RequestScope` to use an advisor outside of controller calls (e.g. jobs)
<2> Use `ServerRequestContext` to retrieve the current request, if present
<3> Check if the request already contains the user object
<4> Retrieving `User` is a potentially expensive operation
<5> Store the `User` in the request for the calls which may follow

[[_granting_permissions]]
== Granting Permissions

You can disable a check for a particular method call, for example for administrator access,
or for calling the code from a serverless function.

The following example shows two options for temporarily disabling permission checks.

.AdministratorPostService.java
[source,java]
----
include::{root-dir}/libs/micronaut-permissions/src/test/groovy/com/agorapulse/permissions/AdministratorPostService.java[lines=20..-1]
----
<1> Annotate with `@GrantPermissions` to disable checks within the method body for any objects, use `target` if you want to specify the object under permission test
<2> Disable checks just for the limited scope with `TemporaryPermissions` object
