name: Gradle RC Watchdog

on:
  schedule:
    - cron:  '0 0 13 * *'

jobs:
  check:
    name: Verify the Latest Gradle Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: check coveralls
        gradle-version: rc
